Repository BV-BRC/BV-BRC-Web, pull requests merged in 2022-12, with the labels that each got.

#496 Move month branches into main alpha branch
  CHANGELOG.md
  package.json
  public/js/p3/widget/RerunUtility.js
  public/js/p3/widget/app/Homology.js
  public/js/p3/widget/app/MetagenomicBinning.js
  public/js/p3/widget/app/Rnaseq.js
  public/js/p3/widget/app/SubspeciesClassification.js
  public/js/p3/widget/app/templates/Homology.html
  public/js/p3/widget/app/templates/MetagenomicBinning.html
  public/js/p3/widget/app/templates/Rnaseq.html
  public/js/release.profile.js
Labels: alpha-month to alpha

#497 Move alpha into develop
  CHANGELOG.md
  package.json
  public/js/p3/widget/RerunUtility.js
  public/js/p3/widget/app/Homology.js
  public/js/p3/widget/app/MetagenomicBinning.js
  public/js/p3/widget/app/Rnaseq.js
  public/js/p3/widget/app/SubspeciesClassification.js
  public/js/p3/widget/app/templates/Homology.html
  public/js/p3/widget/app/templates/MetagenomicBinning.html
  public/js/p3/widget/app/templates/Rnaseq.html
  public/js/release.profile.js
Labels: alpha to develop

#505 fixing trimming checkbox
  public/js/p3/widget/app/Rnaseq.js
Labels: bug fix

#514 Enhancement for viewing nwk and phyloxml files.
  public/js/p3/widget/WorkspaceBrowser.js
Labels: enhancement

#512 update on subspecies class service
  public/js/p3/widget/app/SubspeciesClassification.js
  public/js/p3/widget/viewer/PhylogeneticTree2.js
Labels: enhancement
