Repository BV-BRC/BV-BRC-Web, pull requests merged in 2022-11, with the labels that each got.

#451 bug fix for viewing fasta dna&proteins in GenomeList
  public/js/p3/widget/GridContainer.js
Labels: bug fix, hacktoberfest-accepted

#454 Alpha october2022
  CHANGELOG.md
  package.json
  public/js/p3/widget/VariantLineageDetail.js
  public/js/p3/widget/templates/VariantLineageOverview.html
Labels: hacktoberfest-accepted, feature, alpha-month to alpha

#455 bug fix for viewing fasta dna&proteins in GenomeList
  public/js/p3/widget/GridContainer.js
Labels: bug fix, hacktoberfest-accepted

#457 Alpha october2022
  public/js/p3/widget/GridContainer.js
Labels: bug fix, hacktoberfest-accepted

#458 Alpha --> Develop
  CHANGELOG.md
  package.json
  public/js/p3/widget/GridContainer.js
  public/js/p3/widget/VariantLineageDetail.js
  public/js/p3/widget/templates/VariantLineageOverview.html
Labels: hacktoberfest-accepted, alpha to develop

#459 Develop --> Master
  CHANGELOG.md
  package.json
  public/js/p3/widget/GridContainer.js
  public/js/p3/widget/VariantLineageDetail.js
  public/js/p3/widget/templates/VariantLineageOverview.html
Labels: bug fix, hacktoberfest-accepted, feature, develop to master

#465 Added .var.tsv file for column headers for the TSV viewer
  public/js/p3/widget/TsvCsvFeatures.js
Labels: enhancement

#466 add swine h1 option and reorder virus types
  public/js/p3/widget/app/SubspeciesClassification.js
Labels: feature

#467 bug fix for MSA viewer https://github.com/BV-BRC/issues/issues/948
  public/js/p3/widget/viewer/GenomeAlignment.js
  public/js/p3/widget/viewer/MSATree.js
Labels: bug fix

#469 Move the save button from outside to inside of the viewer.
  public/js/p3/widget/viewer/GenomeAlignment.js
Labels: feature

#470 Bug fix for MSA viewer: https://github.com/BV-BRC/issues/issues/954
  public/js/p3/widget/viewer/MSATree.js
Labels: bug fix

#471 Allow rendering BLAST results without pids or gids.
  public/js/p3/store/HomologyResultMemoryStore.js
  public/js/p3/widget/HomologyResultGrid.js
Labels: bug fix, enhancement

#472 Trigger fasta seqs input validation with onChange
  public/js/p3/widget/app/templates/Homology.html
  public/js/p3/widget/app/templates/MSA.html
Labels: bug fix, enhancement

#473 Changed the loading message when there is no data.
  public/js/p3/store/HomologyResultMemoryStore.js
  public/js/p3/widget/HomologyResultGrid.js
Labels: enhancement

#474 Alpha nov2022
  views/bv-brc-header.ejs
  views/home.ejs
Labels: enhancement
