Repository BV-BRC/BV-BRC-Web, pull requests merged in 2022-09, with the labels that each got.

#399 Hot fix: add contact us link
  views/home.ejs
Labels: hacktoberfest-accepted

#401 Added exact, fuzzy, and range filters to the TSV viewer.
  public/js/p3/store/TsvCsvMemoryStore.js
  public/js/p3/widget/viewer/TSV_CSV.js
Labels: hacktoberfest-accepted

#402 Alpha sept2022
  CHANGELOG.md
  package.json
  public/js/p3/widget/app/ComprehensiveSARS2Analysis.js
  public/js/p3/widget/app/templates/ComprehensiveSARS2Analysis.html
Labels: hacktoberfest-accepted

#403 Searching All Columns was not using a function.
  public/js/p3/store/TsvCsvMemoryStore.js
Labels: bug-fix, hacktoberfest-accepted

#408 Hot fix: add contact us link
  views/home.ejs
Labels: enhancement, hacktoberfest-accepted

#409 Production Release from Develop 3.22.9
  CHANGELOG.md
  app.js
  package.json
  public/js/msa/BVBRC_build.txt
  public/js/msa/dist/msa.js
  public/js/msa/dist/msa.js.map
  public/js/msa/dist/msa.min.gz.css
  public/js/msa/dist/msa.min.gz.js
  public/js/msa/package-lock.json
  public/js/msa/package.json
  public/js/msa/src/views/canvas/CanvasSeqBlock.js
  public/js/msa/stat.seqs.patch
  public/js/p3/app/app.js
  public/js/p3/store/PathwayServiceMemoryStore.js
  public/js/p3/widget/ActionBar.js
  public/js/p3/widget/CopyTooltipDialog.js
  public/js/p3/widget/GridContainer.js
  public/js/p3/widget/PathwayServiceGrid.js
  public/js/p3/widget/PathwayServiceGridContainer.js
  public/js/p3/widget/PathwaysServiceContainer.js
  public/js/p3/widget/Phylogeny2.js
  public/js/p3/widget/ProteinFamiliesServiceGridContainer.js
  public/js/p3/widget/SubsystemServiceMemoryGridContainer.js
  public/js/p3/widget/TsvCsvFeatures.js
  public/js/p3/widget/WorkspaceBrowser.js
  public/js/p3/widget/app/ComprehensiveSARS2Analysis.js
  public/js/p3/widget/app/GenomeDistance.js
  public/js/p3/widget/app/templates/ComprehensiveSARS2Analysis.html
  public/js/p3/widget/app/templates/GenomeDistance.html
  public/js/p3/widget/viewer/MSATree.js
  public/js/p3/widget/viewer/TSV_CSV.js
  public/worker/PathwayServiceWorker.js
  views/bv-brc-header.ejs
  views/header.ejs
  views/javascript.ejs
  views/pages/tools.ejs
Labels: bug-fix, enhancement, dependencies, hacktoberfest-accepted, feature
