Repository BV-BRC/BV-BRC-Web, pull requests merged in 2022-10, with the labels that each got.

#414 Re-bump 3.22.14
  CHANGELOG.md
  package.json
Labels: bug-fix, documentation, hacktoberfest-accepted

#406 Features/subspecies class
  public/js/p3/panels.js
  public/js/p3/widget/JobManager.js
  public/js/p3/widget/Phylogeny2.js
  public/js/p3/widget/TsvCsvFeatures.js
  public/js/p3/widget/WorkspaceBrowser.js
  public/js/p3/widget/app/SubspeciesClassification.js
  public/js/p3/widget/app/templates/SubspeciesClassification.html
  public/js/p3/widget/viewer/PhylogeneticTree2.js
  views/bv-brc-header.ejs
Labels: enhancement, hacktoberfest-accepted, feature

#407 Added the bread-crumbs trail to the MSA and tree viewers
  public/js/p3/widget/Phylogeny2.js
  public/js/p3/widget/viewer/MSATree.js
Labels: enhancement, hacktoberfest-accepted, feature

#415 Changed filter buttons to a select menu on the TSV viewer.
  public/js/p3/widget/viewer/TSV_CSV.js
Labels: enhancement, hacktoberfest-accepted

#416 Changing initial pathways loading to background
  public/js/p3/widget/PathwaysServiceContainer.js
  public/js/p3/widget/SubsystemServiceContainer.js
  public/worker/PathwayServiceWorker.js
Labels: enhancement, hacktoberfest-accepted

#417 bug fix: need to remove URI encode for bread-crumbs path display
  public/js/p3/widget/Phylogeny2.js
  public/js/p3/widget/viewer/MSATree.js
Labels: bug fix

#418 Features/subspecies class
  public/js/p3/panels.js
  public/js/p3/widget/JobManager.js
  public/js/p3/widget/Phylogeny2.js
  public/js/p3/widget/TsvCsvFeatures.js
  public/js/p3/widget/WorkspaceBrowser.js
  public/js/p3/widget/app/SubspeciesClassification.js
  public/js/p3/widget/app/templates/SubspeciesClassification.html
  public/js/p3/widget/viewer/PhylogeneticTree2.js
  views/bv-brc-header.ejs
Labels: enhancement, hacktoberfest-accepted, feature

#419 Alpha october2022 merge to Develop
  CHANGELOG.md
  package.json
  public/js/p3/panels.js
  public/js/p3/widget/JobManager.js
  public/js/p3/widget/PathwaysServiceContainer.js
  public/js/p3/widget/Phylogeny2.js
  public/js/p3/widget/SubsystemServiceContainer.js
  public/js/p3/widget/TsvCsvFeatures.js
  public/js/p3/widget/WorkspaceBrowser.js
  public/js/p3/widget/app/SubspeciesClassification.js
  public/js/p3/widget/app/templates/SubspeciesClassification.html
  public/js/p3/widget/viewer/MSATree.js
  public/js/p3/widget/viewer/PhylogeneticTree2.js
  public/js/p3/widget/viewer/TSV_CSV.js
  public/worker/PathwayServiceWorker.js
  views/bv-brc-header.ejs
Labels: bug fix, enhancement, hacktoberfest-accepted, feature, alpha to develop

#420 Changed 'fuzzy' to 'substring'.
  public/js/p3/widget/viewer/TSV_CSV.js
Labels: bug fix

#421 Updated label to aligned fasta file.
  public/js/p3/widget/app/templates/MSA.html
Labels: enhancement, hacktoberfest-accepted

#422 Alpha sept2022 clark comparativesystes
  public/js/p3/widget/PathwayServiceGrid.js
  public/js/p3/widget/PathwaysServiceContainer.js
  public/worker/PathwayServiceWorker.js
Labels: bug fix, enhancement, hacktoberfest-accepted

#423 Alpha to Beta
  CHANGELOG.md
  package.json
  public/js/p3/widget/PathwayServiceGrid.js
  public/js/p3/widget/PathwaysServiceContainer.js
  public/worker/PathwayServiceWorker.js
Labels: hacktoberfest-accepted, alpha to develop

#424 Features/subspecies class
  public/js/p3/widget/TsvCsvFeatures.js
  public/js/p3/widget/app/SubspeciesClassification.js
  public/js/p3/widget/app/templates/SubspeciesClassification.html
Labels: enhancement, hacktoberfest-accepted

#427 Alpha --> Develop
  CHANGELOG.md
  package.json
  public/js/p3/widget/app/ComprehensiveSARS2Analysis.js
  public/js/p3/widget/app/templates/ComprehensiveSARS2Analysis.html
Labels: enhancement, hacktoberfest-accepted, feature, alpha to develop

#426 updates on tre view for classification
  public/js/p3/widget/viewer/PhylogeneticTree2.js
Labels: enhancement, hacktoberfest-accepted

#428 added breadcrumbs to all CS viewers and fixed facter filters for pathways/subsystems
  public/js/p3/store/SubsystemServiceMemoryStore.js
  public/js/p3/widget/AdvancedSearchFields.js
  public/js/p3/widget/ComparativeSystemsActionBar.js
  public/js/p3/widget/PathwayServiceGrid.js
  public/js/p3/widget/PathwayServiceGridContainer.js
  public/js/p3/widget/PathwaysServiceContainer.js
  public/js/p3/widget/ProteinFamiliesServiceContainer.js
  public/js/p3/widget/SubsystemServiceContainer.js
  public/js/p3/widget/SubsystemServiceMemoryGridContainer.js
  public/js/p3/widget/WorkspaceBrowser.js
Labels: bug fix, enhancement, hacktoberfest-accepted, feature

#429 Alpha october2022
  CHANGELOG.md
  package.json
  public/js/p3/store/SubsystemServiceMemoryStore.js
  public/js/p3/widget/AdvancedSearchFields.js
  public/js/p3/widget/ComparativeSystemsActionBar.js
  public/js/p3/widget/PathwayServiceGrid.js
  public/js/p3/widget/PathwayServiceGridContainer.js
  public/js/p3/widget/PathwaysServiceContainer.js
  public/js/p3/widget/ProteinFamiliesServiceContainer.js
  public/js/p3/widget/SubsystemServiceContainer.js
  public/js/p3/widget/SubsystemServiceMemoryGridContainer.js
  public/js/p3/widget/WorkspaceBrowser.js
  public/js/p3/widget/viewer/PhylogeneticTree2.js
Labels: hacktoberfest-accepted, alpha to develop

#430 Develop
  CHANGELOG.md
  package.json
  public/js/p3/panels.js
  public/js/p3/store/SubsystemServiceMemoryStore.js
  public/js/p3/store/TsvCsvMemoryStore.js
  public/js/p3/widget/AdvancedSearchFields.js
  public/js/p3/widget/ComparativeSystemsActionBar.js
  public/js/p3/widget/JobManager.js
  public/js/p3/widget/PathwayServiceGrid.js
  public/js/p3/widget/PathwayServiceGridContainer.js
  public/js/p3/widget/PathwaysServiceContainer.js
  public/js/p3/widget/Phylogeny2.js
  public/js/p3/widget/ProteinFamiliesServiceContainer.js
  public/js/p3/widget/SubsystemServiceContainer.js
  public/js/p3/widget/SubsystemServiceMemoryGridContainer.js
  public/js/p3/widget/TsvCsvFeatures.js
  public/js/p3/widget/WorkspaceBrowser.js
  public/js/p3/widget/app/ComprehensiveSARS2Analysis.js
  public/js/p3/widget/app/SubspeciesClassification.js
  public/js/p3/widget/app/templates/ComprehensiveSARS2Analysis.html
  public/js/p3/widget/app/templates/MSA.html
  public/js/p3/widget/app/templates/SubspeciesClassification.html
  public/js/p3/widget/viewer/MSA.js
  public/js/p3/widget/viewer/MSATree.js
  public/js/p3/widget/viewer/PhylogeneticTree2.js
  public/js/p3/widget/viewer/TSV_CSV.js
  public/worker/PathwayServiceWorker.js
  views/bv-brc-header.ejs
Labels: bug fix, documentation, enhancement, hacktoberfest-accepted, feature, develop to master

#431 Added fields for choosing a reference sequence.
  public/js/p3/widget/app/AppBase.js
  public/js/p3/widget/app/MSA.js
  public/js/p3/widget/app/templates/MSA.html
Labels: enhancement, hacktoberfest-accepted

#432 Alpha october2022
  CHANGELOG.md
  package.json
  public/js/p3/widget/app/AppBase.js
  public/js/p3/widget/app/MSA.js
  public/js/p3/widget/app/templates/MSA.html
Labels: hacktoberfest-accepted, alpha to develop

#433 Develop
  CHANGELOG.md
  package.json
  public/js/p3/widget/app/AppBase.js
  public/js/p3/widget/app/MSA.js
  public/js/p3/widget/app/templates/MSA.html
Labels: hacktoberfest-accepted, develop to master

#434 Enabled rerun for the Workspace.
  public/js/p3/widget/JobManager.js
  public/js/p3/widget/RerunUtility.js
  public/js/p3/widget/WorkspaceBrowser.js
Labels: enhancement, hacktoberfest-accepted, feature

#435 add influenza h5 option to virus types
  public/js/p3/widget/app/SubspeciesClassification.js
Labels: enhancement, hacktoberfest-accepted

#436 Master dependabot and hot fixes --- > alpha
  package-lock.json
  public/js/msa/package-lock.json
  public/js/msa/package.json
Labels: dependencies, hacktoberfest-accepted, downstream

#437 Bringing Develop up to date with Master branch
  package-lock.json
  public/js/msa/package-lock.json
  public/js/msa/package.json
Labels: dependencies, hacktoberfest-accepted, downstream

#438 Develop
  CHANGELOG.md
  package.json
  public/js/p3/widget/JobManager.js
  public/js/p3/widget/RerunUtility.js
  public/js/p3/widget/WorkspaceBrowser.js
  public/js/p3/widget/app/SubspeciesClassification.js
Labels: bug fix, enhancement, hacktoberfest-accepted, feature, develop to master

#439 added pdb filetype selection and viewer button
  public/js/p3/WorkspaceManager.js
  public/js/p3/widget/WorkspaceBrowser.js
Labels: enhancement, hacktoberfest-accepted

#440 Increased the features queried. Targeted a blank page.
  public/js/p3/widget/viewer/TSV_CSV.js
Labels: enhancement, hacktoberfest-accepted

#442 Base the alignType on the afa file for the MSA viewer.
  public/js/p3/widget/WorkspaceBrowser.js
Labels: enhancement, hacktoberfest-accepted

#443 Changed error message to say Fastq Utilities.
  public/js/p3/widget/app/FastqUtil.js
  public/js/p3/widget/app/templates/FastqUtil.html
Labels: bug fix, hacktoberfest-accepted

#445 Master --> Develop
  CHANGELOG.md
  package.json
  public/js/p3/widget/VariantLineageDetail.js
  public/js/p3/widget/templates/VariantLineageOverview.html
Labels: hacktoberfest-accepted, hot fix

#446 master --> alpha-october2022
  CHANGELOG.md
  package.json
  public/js/p3/widget/VariantLineageDetail.js
  public/js/p3/widget/templates/VariantLineageOverview.html
Labels: hacktoberfest-accepted, hot fix

#447 Test for DNA by looking at frequency of ACTGN.
  public/js/p3/widget/app/AppBase.js
Labels: hacktoberfest-accepted
